name: bak_env
channels:
  - apple
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.2.0
  - abseil-cpp=20211102.0
  - absl-py=2.1.0
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.8
  - aiosignal=1.3.1
  - anyio=4.1.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - astunparse=1.6.3
  - async-lru=1.0.3
  - async-timeout=4.0.3
  - attrs=24.2.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - blas=2.124
  - blas-devel=3.9.0
  - bleach=6.1.0
  - blinker=1.8.2
  - bottleneck=1.3.7
  - brotli=1.0.7
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.11.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - comm=0.2.2
  - contourpy=1.2.0
  - cryptography=39.0.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fftw=3.3.10
  - flatbuffers=24.3.25
  - fonttools=4.51.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozenlist=1.4.1
  - gast=0.4.0
  - giflib=5.2.2
  - google-auth=2.35.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - h11=0.14.0
  - h2=4.1.0
  - hdf5=1.12.1
  - hpack=4.0.0
  - httpcore=1.0.6
  - httpx=0.27.2
  - hyperframe=6.0.1
  - icu=68.2
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.18.1
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.2.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.52.0
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.10.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - llvm-openmp=19.1.0
  - markdown=3.6
  - markupsafe=2.1.5
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - multidict=6.1.0
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.2.2
  - notebook-shim=0.2.4
  - numexpr=2.8.7
  - oauthlib=3.2.2
  - openblas=0.3.27
  - openjpeg=2.5.2
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - overrides=7.7.0
  - packaging=24.1
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - pooch=1.8.2
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.48
  - protobuf=3.20.3
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pygments=2.18.0
  - pyjwt=2.9.0
  - pyobjc-core=10.3.1
  - pyobjc-framework-cocoa=10.3.1
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.9.15
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-flatbuffers=24.3.25
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2024.2
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - pyzmq=25.1.1
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.20.0
  - rsa=4.9
  - scikit-learn=1.5.1
  - scipy=1.10.0
  - seaborn=0.13.2
  - send2trash=1.8.3
  - setuptools=75.1.0
  - six=1.15.0
  - snappy=1.1.10
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow-deps=2.9.0
  - tensorflow-estimator=2.12.0
  - termcolor=1.1.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.3.0
  - tk=8.6.14
  - tomli=2.0.2
  - tornado=6.4.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241003
  - typing_utils=0.1.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.2.3
  - wcwidth=0.2.13
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.0.4
  - wheel=0.35.1
  - wrapt=1.12.1
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.13.1
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - h5py==3.12.1
      - keras==3.6.0
      - libclang==18.1.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - namex==0.0.8
      - ndjson==0.3.1
      - numpy==1.26.4
      - optree==0.13.0
      - pydot==3.0.2
      - pyparsing==3.1.4
      - python-graphviz==0.20.3
      - rich==13.9.2
      - tensorboard==2.16.2
      - tensorflow==2.16.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-macos==2.16.2
      - tensorflow-metal==1.1.0
      - typing-extensions==4.12.2
